### ISSUE TITLE
Ras GIS Import file generation fails for BaldEagle example in QGIS 2.12.3

### ISSUE THREAD

**Issue by karlkastner** [erpas/rgis#20]
An error has occured while executing Python code: 

TypeError: 'NoneType' object has no attribute '**getitem**' 
Traceback (most recent call last):
  File "/home/pia/.qgis2/python/plugins/rivergis/rivergis.py", line 108, in 
    self.ui.actionRASCreateRASGISImport.triggered.connect(lambda: r1d.ras1dCreateRasGisImportFile(self))
  File "/home/pia/.qgis2/python/plugins/rivergis/ras1dFunctions.py", line 466, in ras1dCreateRasGisImportFile
    sdf = rgi.gis_import_file()
  File "/home/pia/.qgis2/python/plugins/rivergis/ras_gis_import.py", line 92, in gis_import_file
    imp = self.header.build_header()
  File "/home/pia/.qgis2/python/plugins/rivergis/ras_gis_import.py", line 169, in build_header
    nor = self.number_of_reaches()
  File "/home/pia/.qgis2/python/plugins/rivergis/ras_gis_import.py", line 120, in number_of_reaches
    nor = int(self.rgis.rdb.run_query(qry, fetch=True)[0][0])
TypeError: 'NoneType' object has no attribute '**getitem**'

Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
QGIS version: 2.12.3-Lyon Lyon, exported

**Comment by erpas** [comment]
Thanks for feedback!
Was the RAS GIS Import file created anyway, or  not?
If not, have you created the network topology, river names and so on before creating the RAS file?

**Comment by erpas** [comment]
No feedback. Closing the issue.
