### ISSUE TITLE
RiverGIS : Python error for Elevations

### ISSUE THREAD

**Issue by IFontain** [erpas/rgis#37]
Hello,

I am using RiverGIS with QGIS 2.18.14, PostGreQSL 9.5.4 64 bits and postgis.  

When I use the option “RAS Geometry / XS Cut Lines Attributes / Elevations” in RIVERGIS, I get the following error message :

“Traceback (most recent call last):
File "C:/Users/POSTE5/.qgis2/python/plugins\rivergis\rivergis.py", line 83, in <lambda>
self.ui.actionRASXSElevations.triggered.connect(lambda: r1d.ras1dXSElevations(self))
File "C:/Users/POSTE5/.qgis2/python/plugins\rivergis\ras1dFunctions.py", line 125, in ras1dXSElevations
prepare_DTMs(rgis)
File "C:/Users/POSTE5/.qgis2/python/plugins\rivergis\rasElevations.py", line 41, in prepare_DTMs
uri = '\'{0}\''.format(rlayer.dataProvider().dataSourceUri())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128) »

Please note that all the previous options (River reach name, stationing, bank station…) were executed  without troubleshooting.  

Have you any ideas ?

Thanks for your help.

Best Regards

Isabelle

**Comment by erpas** [comment]
Could you please save your DTM raster so it has no non-ASCII chars in the path?
Best regards

**Comment by IFontain** [comment]
Hello, I made the following test : the raster was stored in a directory which name contained 'é'. I renamed it to remove 'é', and now it functions...  What's the matter ?

Best Regards
