### ISSUE TITLE
riverGIS Python error...

### ISSUE THREAD

**Issue by Kimjoohun** [erpas/rgis#51]
Dear developer.
I want studing for RiverGIS.
But an error has occurred as below.
Sample data is baldEagle of http://rivergis.com/ras1d_geometry.html

Please solve the problem.

An error has occured while executing Python code:

KeyError: 'StreamCenterlines'
Traceback (most recent call last):
File "C:\Users/Joohoon KIm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\dlg_rasImportDataIntoRasTables.py", line 298, in acceptDialog
self.processLayers(key, data)
File "C:\Users/Joohoon KIm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rivergis\dlg_rasImportDataIntoRasTables.py", line 280, in processLayers
self.rgis.rdb.register[data['className']],
KeyError: 'StreamCenterlines'

Python version 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.16.11-Hannover Hannover, 26cc1c76

python path:
C:/PROGRA1/QGIS311.11/apps/qgis-ltr/./python
C:/Users/Joohoon KIm/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Joohoon KIm/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA1/QGIS311.11/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.16.11\bin\python39.zip
C:\PROGRA1\QGIS311.11\apps\Python39\DLLs
C:\PROGRA1\QGIS311.11\apps\Python39\lib
C:\Program Files\QGIS 3.16.11\bin
C:\PROGRA1\QGIS311.11\apps\Python39
C:\PROGRA1\QGIS311.11\apps\Python39\lib\site-packages
C:\PROGRA1\QGIS311.11\apps\Python39\lib\site-packages\win32
C:\PROGRA1\QGIS311.11\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA1\QGIS311.11\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Joohoon KIm/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Joohoon KIm\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS_FMV
D:/eclipse/plugins/org.python.pydev.core_7.5.0.202001101138/pysrc
H:/
.

**Comment by s1828** [comment]
I have the exact same problem, have you had any luck fixing it?
